services:
  discord-bot:
    image: ghcr.io/elpitagoras14/yt-discord-bot:latest
    container_name: discord-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - APP_ID=${APP_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
